# Generated by Django 5.0.6 on 2024-07-05 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_remove_companymodel_code_and_more'),
        ('users', '0007_usermodel_last_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='company_joining_date',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='last_online',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='code',
            field=models.CharField(error_messages={'unique': 'Код должен быть уникальным.'}, max_length=40, null=True, unique=True, verbose_name='Код для вступления в компанию'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.jobtitlemodel'),
        ),
    ]
