# Generated by Django 4.2.7 on 2024-02-18 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_taskmodel_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='by_user',
        ),
    ]
