# Generated by Django 5.0.6 on 2024-07-05 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_taskmodel_by_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='date',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='commentmodel',
            old_name='by_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='taskmodel',
            old_name='created_at',
            new_name='creation_date',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
