# Generated by Django 5.0.6 on 2024-07-05 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_jobtitlemodel_alter_companymodel_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companymodel',
            name='code',
        ),
        migrations.RemoveField(
            model_name='jobtitlemodel',
            name='add_task',
        ),
        migrations.AddField(
            model_name='jobtitlemodel',
            name='add_task_permission',
            field=models.BooleanField(default=False, verbose_name='Может добавлять и удалять задачи'),
        ),
        migrations.AddField(
            model_name='jobtitlemodel',
            name='add_worker_permission',
            field=models.BooleanField(default=False, verbose_name='Может добавлять и исключать сотрудников'),
        ),
        migrations.AddField(
            model_name='jobtitlemodel',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.companymodel'),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='image',
            field=models.ImageField(blank=True, default='no_image/', upload_to='companies_image/', verbose_name='Логотип'),
        ),
    ]
